### ISSUE TITLE
Verify config GUI works with lower docutil version (and readme file)

### ISSUE THREAD

**Issue by yomach** [qua-platform/py-qua-tools#75]
@nikolaqm - We got a request from a customer to downgrade docutils. Guy already opened a branch for it (downgrade-docutils)
Can you please make sure that everything works?
And in the meanwhile, check that the readme for the GUI is correct

**Comment by nikolaqm** [comment]
There is a problem that has to do with earlier change e1a1c31d5d939749bb408ccfc498fee0442f64ae :
@yomach is there any particular reason why `qualang_tools/config/__init__.py` does not import all elements user can use in config builder? This was deliberately added there so that with `from qualang_tools.config import *` user gets in namespace all config building objects. The API otherwise is very technical (user then has to care about internal hierarchy of folders). Can we change this back?

**Comment by yomach** [comment]
We can change that. There were some issues with the init files, but this part isn't critical...
The main issue is that the config folder has very unrelated tools, I would have preferred to separate to different folders.

You can add these changes to the branch.

**Comment by qguyk** [comment]
@nikolaqm @yomach I suggest we proceed with this issue and merge it, and open a second issue for what Nikola is describing
what do you think?

**Comment by nikolaqm** [comment]
I think I should fix __init__.py before, because things are broken currently, so this is not functional code for the moment.

**Comment by yomach** [comment]
Shouldn't you just import everything you need inside ConfigBuilder?

**Comment by nikolaqm** [comment]
@yomach These objects have same importance as ConfigBuilder, because you "feed" ConfigBuilder object with them.

**Comment by yomach** [comment]
cool, then please fix it and push into the branch.

**Comment by yomach** [comment]
The problem is that importing * imports both the config builder and also some unrelated tools... We need to seriously think about splitting it into two folders

**Comment by nikolaqm** [comment]
Ok, this is fixed (43090a28cb24287dfd4425ad295d7f9346ff867f) and fine with me.

I also removed `builder` from list of accessible things to the user, since the only thing that should be accessible there is `ConfigBuilder`.

Regarding mix of tools: originally, config folder had just ConfigBuilder and its GUI. You could `convert_integration_weights`, `compress_integration_weights`, `plot_integration_weights` under `qualang_tools.config.tools` maybe, but it also makes sense that these are available simply from `from qualang_tools.config import *` as you get all you need for config building. If it is just code organisation, you can move these under `tools` sub-folder, but keep them in `__init__.py` so that single line import stll works?

**Comment by yomach** [comment]
Actually, it's the other way around, originally the config folder had only the tools :) 

I don't think that having a tool subfolder makes sense since the entire package is qualang_**tools**.

I think that the config builder should move to a separate folder which is called "config_builder", as it is a separate tool that is unrelated to the other tools.

@qguyk ?

**Comment by yomach** [comment]
Wait, it's even more confusing.
There are three different things there:

1. Integration weights tools
2. The config builder scripts (in the same folder as the integration weights tools)
3. The config builder GUI (in the server folder, which is a very confusing name).

I think that we should have the under the config 3 different things:
1. The integration weight script
2. The config builder folder
3. The config GUI folder (can be inside #2).

That way, the init file can still be simple, as it will simply import the folders (packages).
@qguyk @nikolaqm Is that ok? can I do it?
